"""Domain schema reference data ported from the old codebase's main/static.py.

Normalized during the port (found while re-reading the old file fresh, not
from memory):

1. SCHEMA["<table>"]["columns"] used to be a dict[str, str] for only 6 of 31
   tables; the other 25 were a one-element `set` wrapping the raw CREATE
   TABLE column list as a single string (e.g. {"id int4 NULL,\n\tname text
   NULL,..."}). The old get_filter/get_table_schema tools worked around this
   by calling str(schema[table]) and doing substring checks - functional,
   but it meant SCHEMA was never a real structured schema. Every table here
   is now a plain dict[str, str] (column name -> SQL type).

2. The old SCHEMA key was "paymentLinks" (capital L), but every lookup in
   agent_common/tools.py normalizes with table_name.lower() first
   (schema[table_name.lower()]) - so that table's schema/filter lookups
   would always raise KeyError in the old code. Fixed here: "paymentlinks".

3. Four tables (customers_deals, deals_units, deals_projects,
   deals_customers) had a leading "customer_id"/"deal_id" annotation
   embedded as dead text inside the raw column-list string - it was never a
   real dict key, so that FK column was effectively missing from their
   schema. The sibling tables built as real dicts (deals_directors,
   deals_agents) do have "deal_id" as a working key, which is clearly the
   intended shape. Restored as a real column here to match them.

DOMAIN[7] (sales+payments) and the "sales"/"payments" tables are kept for
reference but currently unused - no sales_payments sub-agent is being built
for the new architecture.
"""

DOMAIN = [[],
 ['developers', 'projects', 'buildings', 'units'],
 ['employees', 'directors_employees', 'hos_employee', 'teams', 'agents_employee'],
 ['customers', 'customerrequesttrackers', 'customers_deals'],
 ['deals',
  'deals_units',
  'deals_projects',
  'deals_customers',
  'deals_directors',
  'deals_agents',
  'buildings'],
 ['bookings',
  'paymentlinks',
  'projects',
  'buildings',
  'units',
  'employees',
  'agents_employee',
  'customers',
  'brokers'],
 ['paymentsplits',
  'payments',
  'paymentplandetails',
  'paymentlinks',
  'onlinepaymenttransactions',
  'installmentplans',
  'instalmentadjusted',
  'paymenttermitems',
  'paymentterms',
  'projectpaymentplans',
  'projectpaymentterms'],
 ['agents_employee',
  'bookings',
  'brokers',
  'buildings',
  'customers',
  'employees',
  'installmentplans',
  'instalmentadjusted',
  'onlinepaymenttransactions',
  'paymentlinks',
  'paymentplandetails',
  'payments',
  'paymentsplits',
  'paymenttermitems',
  'paymentterms',
  'projectpaymentplans',
  'projectpaymentterms',
  'projects',
  'units']]

SCHEMA = {'developers': {'domain': 'property',
                'columns': {'id': 'int4',
                            'name': 'text',
                            'email': 'text',
                            'operatorname': 'text',
                            'phone': 'text',
                            'portalaccesstype': 'text',
                            'registrationnumber': 'text',
                            'row_txt': 'text',
                            'embedding': 'ev.vector',
                            'embed_name': 'ev.vector',
                            'embed_operatorname': 'ev.vector'}},
 'projects': {'domain': 'property',
              'columns': {'id': 'int4',
                          'name': 'text',
                          'shortname': 'text',
                          'developerid': 'int4',
                          'address': 'text',
                          'location': 'text',
                          'status': 'text',
                          'accountnumber': 'text',
                          'bankaddress': 'text',
                          'bankbranch': 'text',
                          'bankname': 'text',
                          'adminfee': 'text',
                          'corporateaccountname': 'text',
                          'corporateaccountnumber': 'text',
                          'corporatebankaddress': 'text',
                          'corporatebankbranch': 'text',
                          'corporatebankname': 'text',
                          'corporateibannumber': 'text',
                          'escrowaccountname': 'text',
                          'ibannumber': 'text',
                          'currency': 'text',
                          'isavailabiletoportal': 'text',
                          'latitude': 'text',
                          'longitude': 'text',
                          'row_txt': 'text',
                          'embedding': 'ev.vector',
                          'embed_name': 'ev.vector',
                          'embed_shortname': 'ev.vector',
                          'embed_location': 'ev.vector',
                          'embed_bankaddress': 'ev.vector',
                          'embed_bankbranch': 'ev.vector',
                          'embed_bankname': 'ev.vector',
                          'embed_corporateaccountname': 'ev.vector',
                          'embed_corporatebankaddress': 'ev.vector',
                          'embed_corporatebankbranch': 'ev.vector',
                          'embed_corporatebankname': 'ev.vector',
                          'embed_escrowaccountname': 'ev.vector',
                          'embed_isavailabiletoportal': 'ev.vector',
                          'embed_latitude': 'ev.vector',
                          'embed_longitude': 'ev.vector',
                          'embed_address': 'ev.vector'}},
 'buildings': {'domain': 'property',
               'columns': {'id': 'int4',
                           'name': 'text',
                           'shortname': 'text',
                           'developerid': 'int4',
                           'projectid': 'int4',
                           'address': 'text',
                           'location': 'text',
                           'status': 'text',
                           'accountnumber': 'text',
                           'bankaddress': 'text',
                           'bankbranch': 'text',
                           'bankname': 'text',
                           'escrowaccountname': 'text',
                           'ibannumber': 'text',
                           'currency': 'text',
                           'paymenttermid': 'int4',
                           'row_txt': 'text',
                           'embedding': 'ev.vector',
                           'embed_name': 'ev.vector',
                           'embed_shortname': 'ev.vector',
                           'embed_location': 'ev.vector',
                           'embed_bankaddress': 'ev.vector',
                           'embed_bankbranch': 'ev.vector',
                           'embed_bankname': 'ev.vector',
                           'embed_escrowaccountname': 'ev.vector',
                           'embed_address': 'ev.vector'}},
 'units': {'domain': 'property',
           'columns': {'id': 'int4',
                       'name': 'text',
                       'number': 'text',
                       'buildingid': 'text',
                       'unitclusterid': 'text',
                       'availabilitystatus': 'text',
                       'baths': 'text',
                       'bedroom': 'text',
                       'floor': 'text',
                       'furnished': 'text',
                       'kitchen': 'text',
                       'layouthashcode': 'text',
                       'parking': 'text',
                       'plotnumber': 'text',
                       'area': 'text',
                       'price': 'text',
                       'pricepersqft': 'text',
                       'currency': 'text',
                       'description': 'text',
                       'type': 'text',
                       'view': 'text',
                       'row_txt': 'text',
                       'embedding': 'ev.vector',
                       'embed_name': 'ev.vector',
                       'embed_shortname': 'ev.vector',
                       'embed_availabilitystatus': 'ev.vector',
                       'embed_bedroom': 'ev.vector',
                       'embed_furnished': 'ev.vector',
                       'embed_kitchen': 'ev.vector',
                       'embed_parking': 'ev.vector',
                       'embed_description': 'ev.vector',
                       'embed_type': 'ev.vector',
                       'embed_view': 'ev.vector'}},
 'employees': {'domain': 'organization',
               'columns': {'id': 'int4',
                           'name': 'text',
                           'email': 'text',
                           'mobile': 'text',
                           'empcode': 'text',
                           'nationality': 'text',
                           'address': 'text',
                           'role': 'text',
                           'position': 'text',
                           'department': 'text',
                           'section': 'text',
                           'reportingmanagerid': 'text',
                           'employmentdate': 'text',
                           'portalstatus': 'text',
                           'status': 'text',
                           'row_txt': 'text',
                           'embedding': 'ev.vector',
                           'embed_name': 'ev.vector',
                           'embed_nationality': 'ev.vector',
                           'embed_address': 'ev.vector',
                           'embed_role': 'ev.vector',
                           'embed_position': 'ev.vector',
                           'embed_department': 'ev.vector',
                           'embed_section': 'ev.vector'}},
 'directors_employees': {'domain': 'organization',
                         'columns': {'director_sap': 'text',
                                     'director_id': 'int4',
                                     'director_name': 'text',
                                     'director_email': 'text',
                                     'director_mobile': 'text',
                                     'director_empcode': 'text',
                                     'director_nationality': 'text',
                                     'director_address': 'text',
                                     'director_role': 'text',
                                     'director_position': 'text',
                                     'director_department': 'text',
                                     'director_section': 'text',
                                     'director_reportingmanagerid': 'text',
                                     'director_employmentdate': 'text',
                                     'director_portalstatus': 'text',
                                     'director_status': 'text',
                                     'director_row_txt': 'text',
                                     'director_embedding': 'ev.vector',
                                     'director_embed_name': 'ev.vector',
                                     'director_embed_nationality': 'ev.vector',
                                     'director_embed_address': 'ev.vector',
                                     'director_embed_role': 'ev.vector',
                                     'director_embed_position': 'ev.vector',
                                     'director_embed_department': 'ev.vector',
                                     'director_embed_section': 'ev.vector',
                                     'hos_id': 'int4',
                                     'hos_name': 'text',
                                     'hos_email': 'text',
                                     'hos_mobile': 'text',
                                     'hos_empcode': 'text',
                                     'hos_nationality': 'text',
                                     'hos_address': 'text',
                                     'hos_role': 'text',
                                     'hos_position': 'text',
                                     'hos_department': 'text',
                                     'hos_section': 'text',
                                     'hos_reportingmanagerid': 'text',
                                     'hos_employmentdate': 'text',
                                     'hos_portalstatus': 'text',
                                     'hos_status': 'text',
                                     'hos_row_txt': 'text',
                                     'hos_embedding': 'ev.vector',
                                     'hos_embed_name': 'ev.vector',
                                     'hos_embed_nationality': 'ev.vector',
                                     'hos_embed_address': 'ev.vector',
                                     'hos_embed_role': 'ev.vector',
                                     'hos_embed_position': 'ev.vector',
                                     'hos_embed_department': 'ev.vector',
                                     'hos_embed_section': 'ev.vector'}},
 'hos_employee': {'domain': 'organization',
                  'columns': {'id': 'int4',
                              'name': 'text',
                              'email': 'text',
                              'mobile': 'text',
                              'empcode': 'text',
                              'nationality': 'text',
                              'address': 'text',
                              'role': 'text',
                              'position': 'text',
                              'department': 'text',
                              'section': 'text',
                              'reportingmanagerid': 'text',
                              'employmentdate': 'text',
                              'portalstatus': 'text',
                              'status': 'text',
                              'row_txt': 'text',
                              'embedding': 'ev.vector',
                              'embed_name': 'ev.vector',
                              'embed_nationality': 'ev.vector',
                              'embed_address': 'ev.vector',
                              'embed_role': 'ev.vector',
                              'embed_position': 'ev.vector',
                              'embed_department': 'ev.vector',
                              'embed_section': 'ev.vector'}},
 'brokers': {'domain': 'brokers-info',
             'columns': {'id': 'int4',
                         'name': 'text',
                         'email': 'text',
                         'phone': 'text',
                         'nationality': 'text',
                         'address': 'text',
                         'city': 'text',
                         'country': 'text',
                         'zipcode': 'text',
                         'emiratesid': 'text',
                         'type': 'text',
                         'brokeragecompanyid': 'text',
                         'website': 'text',
                         'referred': 'text',
                         'evrepresentativename': 'text',
                         'stage': 'text',
                         'brn': 'text',
                         'orn': 'text',
                         'trn': 'text',
                         'passportexpirydate': 'text',
                         'passportissueddate': 'text',
                         'passportnumber': 'text',
                         'representativeemail': 'text',
                         'representativemobile': 'text',
                         'representativename': 'text',
                         'tradelicensenumber': 'text',
                         'userssoid': 'text',
                         'row_txt': 'text',
                         'embedding': 'ev.vector',
                         'embed_name': 'ev.vector',
                         'embed_nationality': 'ev.vector',
                         'embed_address': 'ev.vector',
                         'embed_city': 'ev.vector',
                         'embed_country': 'ev.vector',
                         'embed_type': 'ev.vector',
                         'embed_stage': 'ev.vector'}},
 'teams': {'domain': 'organization',
           'columns': {'id': 'int4',
                       'name': 'text',
                       'directorid': 'text',
                       'sap': 'text',
                       'row_txt': 'text',
                       'embedding': 'ev.vector',
                       'embed_name': 'ev.vector'}},
 'agents_employee': {'domain': 'organization',
                     'columns': {'id': 'int4',
                                 'name': 'text',
                                 'email': 'text',
                                 'mobile': 'text',
                                 'empcode': 'text',
                                 'nationality': 'text',
                                 'address': 'text',
                                 'role': 'text',
                                 'position': 'text',
                                 'department': 'text',
                                 'section': 'text',
                                 'reportingmanagerid': 'text',
                                 'employmentdate': 'text',
                                 'portalstatus': 'text',
                                 'status': 'text',
                                 'teamid': 'text',
                                 'sap': 'text',
                                 'row_txt': 'text',
                                 'embedding': 'ev.vector',
                                 'embed_name': 'ev.vector',
                                 'embed_nationality': 'ev.vector',
                                 'embed_address': 'ev.vector',
                                 'embed_role': 'ev.vector',
                                 'embed_position': 'ev.vector',
                                 'embed_department': 'ev.vector',
                                 'embed_section': 'ev.vector'}},
 'customers': {'domain': 'crm',
               'columns': {'id': 'int4',
                           'fullnamear': 'text',
                           'fullnameen': 'text',
                           'alternativemobilecountrycode': 'text',
                           'alternativemobileno': 'text',
                           'apartment': 'text',
                           'buildingno': 'text',
                           'city': 'text',
                           'companynamear': 'text',
                           'companynameen': 'text',
                           'country': 'text',
                           'customerindividual_passportexpirydate': 'text',
                           'customerindividual_passportno': 'text',
                           'dldparticipantno': 'text',
                           'dateofbirth': 'text',
                           'eidexpirydate': 'text',
                           'eidissuancedate': 'text',
                           'email': 'text',
                           'emiratesid': 'text',
                           'landline': 'text',
                           'mobile': 'text',
                           'mobilecountrycode': 'text',
                           'nationality': 'text',
                           'operatorname': 'text',
                           'ownershippercentage': 'text',
                           'passportexpirydate': 'text',
                           'passportissuancedate': 'text',
                           'passportno': 'text',
                           'phone': 'text',
                           'position': 'text',
                           'postalcode': 'text',
                           'rejectedreason': 'text',
                           'representativealtmobile': 'text',
                           'representativealtmobilecountrycode': 'text',
                           'representativeemail': 'text',
                           'representativefullnamear': 'text',
                           'representativefullnameen': 'text',
                           'representativemobile': 'text',
                           'representativemobilecountrycode': 'text',
                           'residencevisanumber': 'text',
                           'status': 'text',
                           'street': 'text',
                           'tradelicence': 'text',
                           'tradelicenceexpirydate': 'text',
                           'tradelicenceissuer': 'text',
                           'type': 'text',
                           'visaexpirydate': 'text',
                           'visaissuancedate': 'text',
                           'isfirsttimebuyer': 'text',
                           'row_txt': 'text',
                           'embedding': 'ev.vector',
                           'embed_fullnamear': 'ev.vector',
                           'embed_fullnameen': 'ev.vector',
                           'embed_city': 'ev.vector',
                           'embed_companynamear': 'ev.vector',
                           'embed_companynameen': 'ev.vector',
                           'embed_country': 'ev.vector',
                           'embed_nationality': 'ev.vector',
                           'embed_operatorname': 'ev.vector',
                           'embed_position': 'ev.vector',
                           'embed_representativefullnamear': 'ev.vector',
                           'embed_representativefullnameen': 'ev.vector',
                           'embed_street': 'ev.vector'}},
 'customerrequesttrackers': {'domain': 'crm',
                             'columns': {'id': 'int4',
                                         'actioncount': 'text',
                                         'customerid': 'text',
                                         'isactive': 'text',
                                         'lable': 'text',
                                         'orders': 'text',
                                         'roleid': 'text',
                                         'rolename': 'text',
                                         'status': 'text',
                                         'row_txt': 'text',
                                         'embedding': 'ev.vector',
                                         'embed_label': 'ev.vector',
                                         'embed_rolename': 'ev.vector',
                                         'embed_status': 'ev.vector'}},
 'customers_deals': {'domain': 'crm_sales',
                     'columns': {'customer_id': 'int4',
                                 'name': 'text',
                                 'directorid': 'text',
                                 'projectname': 'text',
                                 'salesoffer': 'text',
                                 'accountmanagername': 'text',
                                 'agentid': 'text',
                                 'unitid': 'text',
                                 'attachecidocuments': 'text',
                                 'bookingdate': 'text',
                                 'bookingtype': 'text',
                                 'brnnumber': 'text',
                                 'cancellationreason': 'text',
                                 'cancelledby': 'text',
                                 'cancelleddate': 'text',
                                 'contactname': 'text',
                                 'dasholding': 'text',
                                 'eciid': 'text',
                                 'agentfreelancername': 'text',
                                 'originalprice': 'text',
                                 'paymentmodel': 'text',
                                 'salesleadsource': 'text',
                                 'shareddealowner': 'text',
                                 'stage': 'text',
                                 'status': 'text',
                                 'unitnumber': 'text',
                                 'rsvsenttoclient': 'text',
                                 'rsvsenttoclientdate': 'text',
                                 'rsvsignedbyclient': 'text',
                                 'spasentforsignature': 'text',
                                 'spasignedbyclient': 'text',
                                 'row_txt': 'text',
                                 'embedding': 'ev.vector',
                                 'embed_name': 'ev.vector',
                                 'embed_projectname': 'ev.vector',
                                 'embed_accountmanagername': 'ev.vector',
                                 'embed_contactname': 'ev.vector',
                                 'embed_agentfreelancername': 'ev.vector',
                                 'creationdate': 'timestamptz'}},
 'deals': {'domain': 'deals',
           'columns': {'id': 'int4',
                       'name': 'text',
                       'directorid': 'text',
                       'projectname': 'text',
                       'salesoffer': 'text',
                       'accountmanagername': 'text',
                       'agentid': 'text',
                       'unitid': 'text',
                       'attachecidocuments': 'text',
                       'bookingdate': 'text',
                       'bookingtype': 'text',
                       'brnnumber': 'text',
                       'cancellationreason': 'text',
                       'cancelledby': 'text',
                       'cancelleddate': 'text',
                       'contactname': 'text',
                       'dasholding': 'text',
                       'eciid': 'text',
                       'agentfreelancername': 'text',
                       'originalprice': 'text',
                       'paymentmodel': 'text',
                       'salesleadsource': 'text',
                       'shareddealowner': 'text',
                       'stage': 'text',
                       'status': 'text',
                       'unitnumber': 'text',
                       'rsvsenttoclient': 'text',
                       'rsvsenttoclientdate': 'text',
                       'rsvsignedbyclient': 'text',
                       'spasentforsignature': 'text',
                       'spasignedbyclient': 'text',
                       'row_txt': 'text',
                       'embedding': 'ev.vector',
                       'embed_name': 'ev.vector',
                       'embed_projectname': 'ev.vector',
                       'embed_accountmanagername': 'ev.vector',
                       'embed_contactname': 'ev.vector',
                       'embed_agentfreelancername': 'ev.vector',
                       'creationdate': 'timestamptz'}},
 'deals_units': {'domain': 'deals',
                 'columns': {'deal_id': 'int4',
                             'name': 'text',
                             'number': 'text',
                             'buildingid': 'text',
                             'unitclusterid': 'text',
                             'availabilitystatus': 'text',
                             'baths': 'text',
                             'bedroom': 'text',
                             'floor': 'text',
                             'furnished': 'text',
                             'kitchen': 'text',
                             'layouthashcode': 'text',
                             'parking': 'text',
                             'plotnumber': 'text',
                             'area': 'text',
                             'price': 'text',
                             'pricepersqft': 'text',
                             'currency': 'text',
                             'description': 'text',
                             'type': 'text',
                             'view': 'text',
                             'row_txt': 'text',
                             'embedding': 'ev.vector',
                             'embed_name': 'ev.vector',
                             'embed_shortname': 'ev.vector',
                             'embed_availabilitystatus': 'ev.vector',
                             'embed_bedroom': 'ev.vector',
                             'embed_furnished': 'ev.vector',
                             'embed_kitchen': 'ev.vector',
                             'embed_parking': 'ev.vector',
                             'embed_description': 'ev.vector',
                             'embed_type': 'ev.vector',
                             'embed_view': 'ev.vector'}},
 'deals_projects': {'domain': 'deals',
                    'columns': {'deal_id': 'int4',
                                'name': 'text',
                                'shortname': 'text',
                                'developerid': 'int4',
                                'address': 'text',
                                'location': 'text',
                                'status': 'text',
                                'accountnumber': 'text',
                                'bankaddress': 'text',
                                'bankbranch': 'text',
                                'bankname': 'text',
                                'adminfee': 'text',
                                'corporateaccountname': 'text',
                                'corporateaccountnumber': 'text',
                                'corporatebankaddress': 'text',
                                'corporatebankbranch': 'text',
                                'corporatebankname': 'text',
                                'corporateibannumber': 'text',
                                'escrowaccountname': 'text',
                                'ibannumber': 'text',
                                'currency': 'text',
                                'isavailabiletoportal': 'text',
                                'latitude': 'text',
                                'longitude': 'text',
                                'row_txt': 'text',
                                'embedding': 'ev.vector',
                                'embed_name': 'ev.vector',
                                'embed_shortname': 'ev.vector',
                                'embed_location': 'ev.vector',
                                'embed_bankaddress': 'ev.vector',
                                'embed_bankbranch': 'ev.vector',
                                'embed_bankname': 'ev.vector',
                                'embed_corporateaccountname': 'ev.vector',
                                'embed_corporatebankaddress': 'ev.vector',
                                'embed_corporatebankbranch': 'ev.vector',
                                'embed_corporatebankname': 'ev.vector',
                                'embed_escrowaccountname': 'ev.vector',
                                'embed_isavailabiletoportal': 'ev.vector',
                                'embed_latitude': 'ev.vector',
                                'embed_longitude': 'ev.vector',
                                'embed_address': 'ev.vector'}},
 'deals_customers': {'domain': 'deals',
                     'columns': {'deal_id': 'int4',
                                 'id': 'int4',
                                 'fullnamear': 'text',
                                 'fullnameen': 'text',
                                 'alternativemobilecountrycode': 'text',
                                 'alternativemobileno': 'text',
                                 'apartment': 'text',
                                 'buildingno': 'text',
                                 'city': 'text',
                                 'companynamear': 'text',
                                 'companynameen': 'text',
                                 'country': 'text',
                                 'customerindividual_passportexpirydate': 'text',
                                 'customerindividual_passportno': 'text',
                                 'dldparticipantno': 'text',
                                 'dateofbirth': 'text',
                                 'eidexpirydate': 'text',
                                 'eidissuancedate': 'text',
                                 'email': 'text',
                                 'emiratesid': 'text',
                                 'landline': 'text',
                                 'mobile': 'text',
                                 'mobilecountrycode': 'text',
                                 'nationality': 'text',
                                 'operatorname': 'text',
                                 'ownershippercentage': 'text',
                                 'passportexpirydate': 'text',
                                 'passportissuancedate': 'text',
                                 'passportno': 'text',
                                 'phone': 'text',
                                 'position': 'text',
                                 'postalcode': 'text',
                                 'rejectedreason': 'text',
                                 'representativealtmobile': 'text',
                                 'representativealtmobilecountrycode': 'text',
                                 'representativeemail': 'text',
                                 'representativefullnamear': 'text',
                                 'representativefullnameen': 'text',
                                 'representativemobile': 'text',
                                 'representativemobilecountrycode': 'text',
                                 'residencevisanumber': 'text',
                                 'status': 'text',
                                 'street': 'text',
                                 'tradelicence': 'text',
                                 'tradelicenceexpirydate': 'text',
                                 'tradelicenceissuer': 'text',
                                 'type': 'text',
                                 'visaexpirydate': 'text',
                                 'visaissuancedate': 'text',
                                 'isfirsttimebuyer': 'text',
                                 'row_txt': 'text',
                                 'embedding': 'ev.vector',
                                 'embed_fullnamear': 'ev.vector',
                                 'embed_fullnameen': 'ev.vector',
                                 'embed_city': 'ev.vector',
                                 'embed_companynamear': 'ev.vector',
                                 'embed_companynameen': 'ev.vector',
                                 'embed_country': 'ev.vector',
                                 'embed_nationality': 'ev.vector',
                                 'embed_operatorname': 'ev.vector',
                                 'embed_position': 'ev.vector',
                                 'embed_representativefullnamear': 'ev.vector',
                                 'embed_representativefullnameen': 'ev.vector',
                                 'embed_street': 'ev.vector'}},
 'deals_directors': {'domain': 'organization',
                     'columns': {'deal_id': 'int4',
                                 'director_sap': 'text',
                                 'director_id': 'int4',
                                 'director_name': 'text',
                                 'director_email': 'text',
                                 'director_mobile': 'text',
                                 'director_empcode': 'text',
                                 'director_nationality': 'text',
                                 'director_address': 'text',
                                 'director_role': 'text',
                                 'director_position': 'text',
                                 'director_department': 'text',
                                 'director_section': 'text',
                                 'director_reportingmanagerid': 'text',
                                 'director_employmentdate': 'text',
                                 'director_portalstatus': 'text',
                                 'director_status': 'text',
                                 'director_row_txt': 'text',
                                 'director_embedding': 'ev.vector',
                                 'director_embed_name': 'ev.vector',
                                 'director_embed_nationality': 'ev.vector',
                                 'director_embed_address': 'ev.vector',
                                 'director_embed_role': 'ev.vector',
                                 'director_embed_position': 'ev.vector',
                                 'director_embed_department': 'ev.vector',
                                 'director_embed_section': 'ev.vector',
                                 'hos_id': 'int4',
                                 'hos_name': 'text',
                                 'hos_email': 'text',
                                 'hos_mobile': 'text',
                                 'hos_empcode': 'text',
                                 'hos_nationality': 'text',
                                 'hos_address': 'text',
                                 'hos_role': 'text',
                                 'hos_position': 'text',
                                 'hos_department': 'text',
                                 'hos_section': 'text',
                                 'hos_reportingmanagerid': 'text',
                                 'hos_employmentdate': 'text',
                                 'hos_portalstatus': 'text',
                                 'hos_status': 'text',
                                 'hos_row_txt': 'text',
                                 'hos_embedding': 'ev.vector',
                                 'hos_embed_name': 'ev.vector',
                                 'hos_embed_nationality': 'ev.vector',
                                 'hos_embed_address': 'ev.vector',
                                 'hos_embed_role': 'ev.vector',
                                 'hos_embed_position': 'ev.vector',
                                 'hos_embed_department': 'ev.vector',
                                 'hos_embed_section': 'ev.vector'}},
 'deals_agents': {'domain': 'organization',
                  'columns': {'deal_id': 'int4',
                              'id': 'int4',
                              'name': 'text',
                              'email': 'text',
                              'mobile': 'text',
                              'empcode': 'text',
                              'nationality': 'text',
                              'address': 'text',
                              'role': 'text',
                              'position': 'text',
                              'department': 'text',
                              'section': 'text',
                              'reportingmanagerid': 'text',
                              'employmentdate': 'text',
                              'portalstatus': 'text',
                              'status': 'text',
                              'teamid': 'text',
                              'sap': 'text',
                              'row_txt': 'text',
                              'embedding': 'ev.vector',
                              'embed_name': 'ev.vector',
                              'embed_nationality': 'ev.vector',
                              'embed_address': 'ev.vector',
                              'embed_role': 'ev.vector',
                              'embed_position': 'ev.vector',
                              'embed_department': 'ev.vector',
                              'embed_section': 'ev.vector'}},
 'bookings': {'domain': 'sales',
              'columns': {'id': 'int4',
                          'unitid': 'int4',
                          'originalprice': 'float8',
                          'agreedprice': 'float8',
                          'transferredtodeal': 'bool',
                          'customerid': 'int4',
                          'projectid': 'int4',
                          'stage': 'text',
                          'agentid': 'int4',
                          'managerid': 'int4',
                          'headofsalesid': 'int4',
                          'csoid': 'int4',
                          'layout': 'text',
                          'brokerid': 'int4',
                          'createdby': 'text',
                          'creationdate': 'text',
                          'isdeleted': 'bool',
                          'paymentlinkid': 'int4',
                          'bookingreferenceid': 'text',
                          'draftedamount': 'float8',
                          'row_text': 'text',
                          'embedding': 'ev.vector'}},
 'paymentlinks': {'domain': 'sales',
                  'columns': {'id': 'int4',
                              'amount': 'float8',
                              'currency': 'text',
                              'paymenttype': 'text',
                              'paymenturl': 'text',
                              'status': 'text',
                              'expirydate': 'text',
                              'refno': 'text',
                              'paymentlinkreferenceid': 'text',
                              'projectid': 'int4',
                              'agentid': 'int4',
                              'createdby': 'text',
                              'creationdate': 'text',
                              'isdeleted': 'bool',
                              'issplited': 'bool',
                              'remainingamount': 'float8',
                              'servicechargepercentage': 'float8',
                              'embed_paymenttype': 'ev.vector',
                              'embed_status': 'ev.vector',
                              'row_text': 'text',
                              'embedding': 'ev.vector'}},
 'payments': {'domain': 'payments',
              'columns': {'id': 'int4',
                          'paymentreceiptdetailsname': 'text',
                          'status': 'text',
                          'amount': 'float8',
                          'account': 'text',
                          'paymentmethod': 'text',
                          'dateofreceipt': 'text',
                          'chqddttnumber': 'text',
                          'dateoftransaction': 'text',
                          'chequedepositdate': 'text',
                          'chequereturneddate': 'text',
                          'dealid': 'int4',
                          'receivedbyevdate': 'text',
                          'transferredtodeveloperdate': 'text',
                          'receiveddate': 'text',
                          'popreference': 'int4',
                          'isformrequested': 'bool',
                          'isloading': 'bool',
                          'currency': 'text',
                          'customerid': 'int4',
                          'paymentstatus': 'text',
                          'createdby': 'text',
                          'creationdate': 'text',
                          'isdeleted': 'bool',
                          'embed_paymentreceiptdetailsname': 'ev.vector',
                          'embed_status': 'ev.vector',
                          'embed_account': 'ev.vector',
                          'embed_paymentmethod': 'ev.vector',
                          'embed_paymentstatus': 'ev.vector',
                          'row_text': 'text',
                          'embedding': 'ev.vector'}},
 'installmentplans': {'domain': 'payments',
                      'columns': {'id': 'int4',
                                  'name': 'text',
                                  'priority': 'int4',
                                  'percentage': 'float8',
                                  'amount': 'float8',
                                  'duedate': 'text',
                                  'paymentdate': 'text',
                                  'settled': 'bool',
                                  'status': 'text',
                                  'paidamount': 'float8',
                                  'remainingamount': 'float8',
                                  'dealid': 'int4',
                                  'accounttype': 'text',
                                  'createdby': 'text',
                                  'creationdate': 'text',
                                  'isdeleted': 'bool',
                                  'embed_name': 'ev.vector',
                                  'embed_status': 'ev.vector',
                                  'embed_accounttype': 'ev.vector',
                                  'row_text': 'text',
                                  'embedding': 'ev.vector'}},
 'instalmentadjusted': {'domain': 'payments',
                        'columns': {'id': 'int4',
                                    'instalmenttype': 'text',
                                    'amount': 'float8',
                                    'paymentmethod': 'text',
                                    'paymentid': 'int4',
                                    'instalmentplanid': 'int4',
                                    'accounttype': 'text',
                                    'currency': 'text',
                                    'createdby': 'text',
                                    'creationdate': 'text',
                                    'isdeleted': 'bool',
                                    'embed_instalmenttype': 'ev.vector',
                                    'embed_paymentmethod': 'ev.vector',
                                    'embed_accounttype': 'ev.vector',
                                    'row_text': 'text',
                                    'embedding': 'ev.vector'}},
 'onlinepaymenttransactions': {'domain': 'payments',
                               'columns': {'id': 'int4',
                                           'transactionnumber': 'text',
                                           'amount': 'float8',
                                           'status': 'text',
                                           'paymentlink': 'text',
                                           'creationdatetime': 'text',
                                           'businessentityid': 'int4',
                                           'businessentitytype': 'int4',
                                           'embed_status': 'ev.vector',
                                           'row_text': 'text',
                                           'embedding': 'ev.vector'}},
 'paymentplandetails': {'domain': 'payments',
                        'columns': {'id': 'int4',
                                    'salesproposalid': 'int4',
                                    'evinstalment': 'text',
                                    'duedate': 'text',
                                    'amount': 'float8',
                                    'percentage': 'float8',
                                    'paymenttermitemid': 'int4',
                                    'createdby': 'text',
                                    'creationdate': 'text',
                                    'isdeleted': 'bool',
                                    'embed_evinstalment': 'ev.vector',
                                    'row_text': 'text',
                                    'embedding': 'ev.vector'}},
 'paymentsplits': {'domain': 'payments',
                   'columns': {'id': 'int4',
                               'paymentlinkid': 'text',
                               'amount': 'float8',
                               'status': 'text',
                               'isfullpaymentamount': 'bool',
                               'createdby': 'text',
                               'creationdate': 'text',
                               'isdeleted': 'bool',
                               'embed_status': 'ev.vector',
                               'row_text': 'text',
                               'embedding': 'ev.vector'}},
 'paymentterms': {'domain': 'payments',
                  'columns': {'id': 'int4',
                              'ptid': 'text',
                              'adminfee': 'float8',
                              'dldfee': 'float8',
                              'name': 'text',
                              'exchangerate': 'float8',
                              'status': 'bool',
                              'currency': 'text',
                              'bedtype': 'text',
                              'createdby': 'text',
                              'creationdate': 'text',
                              'isdeleted': 'bool',
                              'embed_name': 'ev.vector',
                              'embed_status': 'ev.vector',
                              'embed_bedtype': 'ev.vector',
                              'row_text': 'text',
                              'embedding': 'ev.vector'}},
 'paymenttermitems': {'domain': 'payments',
                      'columns': {'id': 'int4',
                                  'name': 'text',
                                  'gap': 'int4',
                                  'percentage': 'float8',
                                  'duedate': 'text',
                                  'paymenttermid': 'int4',
                                  'milestonegaptype': 'text',
                                  'createdby': 'text',
                                  'creationdate': 'text',
                                  'isdeleted': 'bool',
                                  'embed_name': 'ev.vector',
                                  'embed_milestonegaptype': 'ev.vector',
                                  'row_text': 'text',
                                  'embedding': 'ev.vector'}},
 'projectpaymentplans': {'domain': 'payments',
                         'columns': {'id': 'int4',
                                     'projectid': 'int4',
                                     'paymenttermid': 'int4',
                                     'createdby': 'text',
                                     'creationdate': 'text',
                                     'isdeleted': 'bool',
                                     'row_text': 'text',
                                     'embedding': 'ev.vector'}},
 'projectpaymentterms': {'domain': 'payments',
                         'columns': {'id': 'int4',
                                     'layout': 'text',
                                     'projectid': 'int4',
                                     'minimumamount': 'float8',
                                     'embed_layout': 'ev.vector',
                                     'row_text': 'text',
                                     'embedding': 'ev.vector'}},
 'projectpayment': {'domain': 'payments viwe (not yet) projectpaymentterms, projectpaymentplans ',
                    'columns': {'id': 'int',
                                'projectid': 'int4',
                                'layout': 'text',
                                'minimumamount': 'decimal',
                                'projectname': 'text',
                                'projectshortname': 'text',
                                'projectdeveloperid': 'int4',
                                'projectaddress': 'text',
                                'projectlocation': 'text',
                                'projectstatus': 'text',
                                'projectaccountnumber': 'text',
                                'projectbankaddress': 'text',
                                'projectbankbranch': 'text',
                                'projectbankname': 'text',
                                'projectadminfee': 'text',
                                'projectcorporateaccountname': 'text',
                                'projectcorporateaccountnumber': 'text',
                                'projectcorporatebankaddress': 'text',
                                'projectcorporatebankbranch': 'text',
                                'projectcorporatebankname': 'text',
                                'projectcorporateibannumber': 'text',
                                'projectescrowaccountname': 'text',
                                'projectibannumber': 'text',
                                'projectcurrency': 'text',
                                'projectisavailabiletoportal': 'text',
                                'projectlatitude': 'text',
                                'projectlongitude': 'text',
                                'embed_projectname': 'ev.vector',
                                'embed_projectshortname': 'ev.vector',
                                'embed_projectlocation': 'ev.vector',
                                'embed_projectbankaddress': 'ev.vector',
                                'embed_projectbankbranch': 'ev.vector',
                                'embed_projectbankname': 'ev.vector',
                                'embed_projectcorporateaccountname': 'ev.vector',
                                'embed_projectcorporatebankaddress': 'ev.vector',
                                'embed_projectcorporatebankbranch': 'ev.vector',
                                'embed_projectcorporatebankname': 'ev.vector',
                                'embed_projectescrowaccountname': 'ev.vector',
                                'embed_projectisavailabiletoportal': 'ev.vector',
                                'embed_projectlatitude': 'ev.vector',
                                'embed_projectlongitude': 'ev.vector',
                                'createdby': 'text',
                                'creationdate': 'text',
                                'isdeleted': 'bool',
                                'row_txt': 'text',
                                'embedding': 'ev.vector'}}}

WORD_SEARCH_LIST: dict[str, list[str]] = {'developers': ['portalaccesstype'],
 'projects': ['status', 'isavailabiletoportal'],
 'buildings': ['availabilitystatus',
               'availab',
               'bedroom',
               'currency',
               'status',
               'isavailabiletoportal'],
 'units': ['availabilitystatus', 'currency', 'baths', 'bedroom', 'furnished', 'kitchen', 'type'],
 'employees': ['portalstatus', 'status'],
 'directors_employees': ['director_portalstatus',
                         'director_status',
                         'hos_portalstatus',
                         'hos_status'],
 'hos_employee': ['portalstatus', 'status'],
 'brokers': ['stage', 'city', 'country'],
 'teams': [],
 'agents_employee': ['portalstatus', 'status'],
 'customers': ['country', 'city', 'status'],
 'customerrequesttrackers': ['lable', 'status'],
 'customers_deals': ['name', 'stage', 'status', 'country', 'city'],
 'deals': ['name', 'type', 'stage', 'status', 'city', 'country'],
 'deals_customers': ['country', 'city', 'status'],
 'deals_units': ['stage',
                 'status',
                 'salesleadsource',
                 'availabilitystatus',
                 'bedroom',
                 'furnished',
                 'kitchen',
                 'parking',
                 'currency',
                 'type',
                 'availability',
                 'bookingtype'],
 'deals_projects': ['salesleadsource', 'stage', 'status', 'isavailabiletoportal'],
 'deals_directors': ['director_portalstatus', 'director_status', 'hos_portalstatus', 'hos_status'],
 'deals_agents': ['portalstatus', 'status'],
 'bookings': ['Stage', 'layout', 'TransferredToDeal'],
 'paymentlinks': ['paymenttype', 'status', 'currency'],
 'paymentsplits': ['status'],
 'payments': ['paymentreceiptdetailsname',
              'status',
              'account',
              'paymentmethod',
              'chqddttnumber',
              'currency',
              'paymentstatus'],
 'paymentplandetails': [],
 'onlinepaymenttransactions': ['status'],
 'installmentplans': ['name', 'status', 'accounttype'],
 'instalmentadjusted': ['instalmenttype', 'paymentmethod', 'accounttype'],
 'paymenttermitems': ['name', 'milestonegaptype'],
 'paymentterms': ['name', 'bedtype', 'status', 'currency'],
 'projectpaymentplans': [],
 'projectpaymentterms': ['layout']}

OPERATION_SEARCH_LIST: dict[str, list[str]] = {'developers': ['id', 'phone', 'portalaccesstype', 'registrationnumber'],
 'projects': ['id',
              'developerid',
              'accountnumber',
              'adminfee',
              'corporateaccountnumber',
              'corporateibannumber',
              'ibannumber',
              'latitude',
              'longitude'],
 'buildings': ['id',
               'developerid',
               'projectid',
               'accountnumber',
               'ibannumber',
               'paymenttermid',
               'latitude',
               'longitude'],
 'units': ['id',
           'number',
           'buildingid',
           'unitclusterid',
           'baths',
           'floor',
           'layouthashcode',
           'plotnumber',
           'area',
           'price',
           'pricepersqft'],
 'employees': ['id', 'mobile', 'empcode', 'reportingmanagerid', 'email'],
 'directors_employees': ['director_id',
                         'director_mobile',
                         'director_empcode',
                         'director_reportingmanagerid',
                         'director_sap',
                         'director_email',
                         'hos_email',
                         'hos_id',
                         'hos_mobile',
                         'hos_empcode',
                         'hos_reportingmanagerid'],
 'hos_employee': ['id', 'mobile', 'empcode', 'reportingmanagerid', 'email'],
 'brokers': ['id',
             'phone',
             'zipcode',
             'emiratesid',
             'brokeragecompanyid',
             'email',
             'passportnumber',
             'representativeemail',
             'representativemobile',
             'representativename',
             'tradelicensenumber',
             'userssoid'],
 'agents_employee': ['id', 'mobile', 'empcode', 'reportingmanagerid', 'teamid', 'sap', 'email'],
 'teams': [],
 'customers': ['id',
               'mobile',
               'mobilecountrycode',
               'alternativemobileno',
               'alternativemobilecountrycode',
               'email',
               'street',
               'landline',
               'phone',
               'apartment',
               'buildingno',
               'postalcode',
               'ownershippercentage'],
 'customerrequesttrackers': ['id', 'customerid', 'actioncount', 'isactive', 'roleid', 'order'],
 'customers_deals': ['customer_id', 'id', 'directorid', 'agentid', 'unitid', 'street'],
 'deals': ['id', 'directorid', 'agentid', 'unitid'],
 'deals_units': ['deal_id',
                 'directorid',
                 'agentid',
                 'id',
                 'buildingid',
                 'unitclusterid',
                 'price_range',
                 'area',
                 'price',
                 'pricepersqft',
                 'number',
                 'baths',
                 'floor',
                 'salesoffer',
                 'paymentmodel',
                 'unitnumber'],
 'deals_projects': ['id',
                    'directorid',
                    'agentid',
                    'unitid',
                    'bookingtype',
                    'stage',
                    'status',
                    'originalprice',
                    'deal_id',
                    'latitude',
                    'longitude'],
 'deals_customers': ['deal_id',
                     'id',
                     'mobile',
                     'mobilecountrycode',
                     'alternativemobileno',
                     'alternativemobilecountrycode',
                     'email',
                     'street',
                     'landline',
                     'phone',
                     'apartment',
                     'buildingno',
                     'postalcode',
                     'ownershippercentage'],
 'deals_agents': ['deal_id',
                  'id',
                  'mobile',
                  'empcode',
                  'reportingmanagerid',
                  'teamid',
                  'email',
                  'sap'],
 'deals_directors': ['deal_id',
                     'director_id',
                     'director_mobile',
                     'director_empcode',
                     'director_reportingmanagerid',
                     'director_sap',
                     'director_email',
                     'hos_email',
                     'hos_id',
                     'hos_mobile',
                     'hos_empcode',
                     'hos_reportingmanagerid'],
 'bookings': ['id',
              'unitid',
              'originalprice',
              'agreedprice',
              'customerid',
              'projectid',
              'agentid',
              'managerid',
              'headofsalesid',
              'csoid',
              'brokerid',
              'createdby',
              'isdeleted',
              'paymentlinkid',
              'bookingreferenceid',
              'draftedamount'],
 'paymentlinks': ['id',
                  'amount',
                  'payment_url',
                  'ref_no',
                  'payment_link_reference_id',
                  'project_id',
                  'agent_id',
                  'created_by',
                  'is_deleted',
                  'is_splited',
                  'remaining_amount',
                  'service_charge_percentage'],
 'paymentsplits': ['id',
                   'PaymentLinkId',
                   'amount',
                   'isfullpaymentamount',
                   'createdby',
                   'isdeleted'],
 'payments': ['id',
              'amount',
              'dealid',
              'popreference',
              'isformrequested',
              'isloading',
              'customerid',
              'createdby',
              'isdeleted'],
 'paymentplandetails': ['id',
                        'salesproposalid',
                        'paymenttermitemid',
                        'amount',
                        'percentage',
                        'createdby',
                        'isdeleted'],
 'onlinepaymenttransactions': ['id',
                               'businessentityid',
                               'businessentitytype',
                               'amount',
                               'transactionnumber'],
 'installmentplans': ['id',
                      'priority',
                      'percentage',
                      'amount',
                      'settled',
                      'paidamount',
                      'remainingamount',
                      'dealid',
                      'createdby',
                      'isdeleted'],
 'instalmentadjusted': ['id',
                        'amount',
                        'paymentid',
                        'instalmentplanid',
                        'currency',
                        'createdby',
                        'isdeleted'],
 'paymenttermitems': ['id', 'gap', 'percentage', 'paymenttermid'],
 'paymentterms': ['id', 'ptid', 'adminfee', 'dldfee', 'exchangerate', 'createdby', 'isdeleted'],
 'projectpaymentplans': ['id', 'projectid', 'paymenttermid', 'createdby', 'isdeleted'],
 'projectpaymentterms': ['id', 'projectid', 'minimumamount']}

SEMANTIC_SEARCH_LIST: dict[str, list[str]] = {'developers': ['name', 'operatorname'],
 'projects': ['name',
              'shortname',
              'location',
              'bankaddress',
              'bankbranch',
              'bankname',
              'corporateaccountname',
              'corporatebankaddress',
              'corporatebankbranch',
              'corporatebankname',
              'escrowaccountname',
              'address'],
 'units': ['name', 'shortname', 'description', 'view'],
 'buildings': ['name',
               'shortname',
               'location',
               'bankaddress',
               'bankbranch',
               'bankname',
               'escrowaccountname',
               'address'],
 'employees': ['name', 'nationality', 'address', 'role', 'position', 'department', 'section'],
 'hos_employee': ['name', 'nationality', 'address', 'role', 'position', 'department', 'section'],
 'directors_employees': ['director_name',
                         'director_nationality',
                         'director_address',
                         'director_role',
                         'director_position',
                         'director_department',
                         'director_section',
                         'hos_name',
                         'hos_nationality',
                         'hos_address',
                         'hos_role',
                         'hos_position',
                         'hos_department',
                         'hos_section'],
 'teams': ['name'],
 'agents_employee': ['name', 'nationality', 'address', 'role', 'position', 'department', 'section'],
 'brokers': ['name', 'nationality', 'address', 'evrepresentativename'],
 'customers': ['fullnameen',
               'fullnamear',
               'nationality',
               'companynamear',
               'companynameen',
               'operatorname',
               'position'],
 'customerrequesttrackers': ['rolename'],
 'customers_deals': ['fullnameen',
                     'fullnamear',
                     'nationality',
                     'companynamear',
                     'companynameen',
                     'operatorname',
                     'position',
                     'deal_name',
                     'projectname',
                     'accountmanagername'],
 'deals': ['address', 'role', 'position', 'section', 'department', 'nationality'],
 'deals_units': ['deal_name',
                 'projectname',
                 'paymentmodel',
                 'contactname',
                 'agentfreelancername',
                 'accountmanagername',
                 'unit_name',
                 'description',
                 'unit_view',
                 'project',
                 'booking'],
 'deals_projects': ['name',
                    'projectname',
                    'accountmanagername',
                    'contactname',
                    'agentfreelancername',
                    'project_name',
                    'project_shortname',
                    'project_location',
                    'bankaddress',
                    'bankbranch',
                    'bankname',
                    'corporateaccountname',
                    'corporatebankaddress',
                    'corporatebankbranch',
                    'corporatebankname',
                    'escrowaccountname'],
 'deals_directors': ['director_name',
                     'director_nationality',
                     'director_address',
                     'director_role',
                     'director_position',
                     'director_department',
                     'director_section',
                     'hos_name',
                     'hos_nationality',
                     'hos_address',
                     'hos_role',
                     'hos_position',
                     'hos_department',
                     'hos_section'],
 'deals_agents': ['name', 'nationality', 'address', 'role', 'position', 'department', 'section'],
 'deals_customers': ['fullnameen',
                     'fullnamear',
                     'nationality',
                     'companynamear',
                     'companynameen',
                     'operatorname',
                     'position',
                     'deal_name',
                     'projectname',
                     'accountmanagername'],
 'bookings': [],
 'paymentlinks': [],
 'paymentsplits': [],
 'payments': [],
 'paymentplandetails': ['evinstalment'],
 'onlinepaymenttransactions': [],
 'installmentplans': [],
 'instalmentadjusted': [],
 'paymenttermitems': [],
 'paymentterms': [],
 'projectpaymentplans': [],
 'projectpaymentterms': []}

DATETIME_SEARCH_LIST: dict[str, list[str]] = {'developers': [],
 'projects': [],
 'units': [],
 'buildings': [],
 'employees': ['employmentdate'],
 'hos_employee': ['employmentdate'],
 'directors_employees': ['director_employmentdate', 'hos_employmentdate'],
 'teams': [],
 'agents_employee': ['employmentdate'],
 'brokers': ['passportissueddate', 'passportexpirydate'],
 'customers': [],
 'customerrequesttrackers': [],
 'customers_deals': [],
 'deals': [],
 'deals_units': ['bookingdate'],
 'deals_projects': ['bookingdate'],
 'deals_directors': ['director_employmentdate', 'hos_employmentdate'],
 'deals_agents': ['employmentdate'],
 'deals_customers': [],
 'bookings': ['creationdate'],
 'paymentlinks': ['expiry_date', 'creation_date'],
 'paymentsplits': ['creationdate'],
 'payments': ['dateofreceipt',
              'dateoftransaction',
              'chequedepositdate',
              'chequereturneddate',
              'receivedbyevdate',
              'transferredtodeveloperdate',
              'receiveddate',
              'creationdate'],
 'paymentplandetails': ['duedate', 'creationdate'],
 'onlinepaymenttransactions': ['creationdatetime'],
 'installmentplans': ['duedate', 'paymentdate', 'creationdate'],
 'instalmentadjusted': ['creationdate'],
 'paymenttermitems': ['duedate'],
 'paymentterms': ['creationdate'],
 'projectpaymentplans': ['creationdate'],
 'projectpaymentterms': []}


# ============================================================
# FILTER_TYPES: dict[table][column] -> filter type explanation
# ============================================================
# TODO(Maryam): implement _build_filter_types().
#
# Same idea as: instead of checking a product against express_list /
# standard_list / economy_list every time you print its shipping label,
# you walk those lists ONCE at startup and stamp each product with its
# label into one dict - then printing a label later is a plain lookup,
# no re-checking membership in three lists per call.
#
# Here the "product" is a (table, column) pair and the "label" is the
# filter-type explanation string the LLM sees. The old get_filter() in
# agent_common/tools.py recomputed this per call, per column, by checking
# membership in 4 lists in this exact priority order (first match wins):
#   1. SEMANTIC_SEARCH_LIST  -> vector filter text
#   2. WORD_SEARCH_LIST      -> ILIKE filter text
#   3. OPERATION_SEARCH_LIST -> operator filter text
#   4. DATETIME_SEARCH_LIST  -> cast-to-timestamp filter text
#   5. (none of the above)   -> generic "any type of filters" text
# then, AFTER that priority chain, two special cases unconditionally
# override whatever the chain produced (they win regardless of which list
# the column was found in, or even if it wasn't found in any of them):
#   - column name in {"name", "shortname"}   -> combined name/shortname
#     vector-search text (see old get_filter for exact wording)
#   - column name in {"address", "location"} -> combined address/location
#     vector-search text (see old get_filter for exact wording)
#
# _build_filter_types() should walk SCHEMA once and, for every
# (table, column) pair that actually exists in that table's columns,
# apply the same priority chain + overrides to produce one filter-type
# string, returning dict[table_name, dict[column_name, str]].
#
# SqlToolAdapter._get_filter(table, columns) then becomes a plain lookup
# into FILTER_TYPES[table] per requested column (with an "unknown column"
# message for anything not in that table's SCHEMA) - no per-call list
# scanning.


def _build_filter_types() -> dict[str, dict[str, str]]:
    raise NotImplementedError


# Left commented until _build_filter_types() is implemented - otherwise
# just importing SCHEMA/DOMAIN from this module (needed right now elsewhere)
# would crash on the NotImplementedError above.
# FILTER_TYPES: dict[str, dict[str, str]] = _build_filter_types()
